### ISSUE TITLE
Feeling Special Mistake Bug

### ISSUE THREAD

**Issue by InfernoStats** [QuestingPet/ToaMistakeTracker#1]
After sending a raid with the plugin, it appears that it counts you as getting hit by Akkha's memory special attack when Feeling Special is  turned on even if you did not take damage.

**Comment by QuestingPet** [comment]
Thanks for the feedback! I haven't been playing much the past two weeks so I wouldn't have been able to catch this myself.

Looks like Jagex recently changed how the timing of the special attack works w.r.t. the graphics objects spawning. This should be fixed now in [055791aca0c47929f7077726cc7fe3dda59f465e](https://github.com/QuestingPet/ToaMistakeTracker/commit/055791aca0c47929f7077726cc7fe3dda59f465e).

More info in the Akkha detector documentation, but I'll paste it here for convenience in case you care:

```
* UPDATE: As of 10/03/2022 Jagex recently changed Akkha's quadrant special behavior in the past week or two. Now, all
 * of the graphics objects spawn immediately, with a 1-tick delay. Seemingly this is to stop cheesing in the corners
 * where some of the orbs spawn 1-tick after others and you can "skip". We still need to account for the explode
 * special, as there is a 0-tick delay for those hitting the player.
```

I'll comment again when this gets updated in the hub. Thanks again for catching and reporting!

**Comment by QuestingPet** [comment]
This has been merged and should be updated in the hub. Make sure to manually update the plugin if you don't restart the client. Thanks!

**Comment by nbulischeck** [comment]
Thanks for fixing that so soon 😃
