### ISSUE TITLE
Taking a P2 warden divine projectile counts as a mistake even after it is downed

### ISSUE THREAD

**Issue by Nightfirecat** [QuestingPet/ToaMistakeTracker#2]
Downing P2 warden to bring its core out causes damage from the divine projectile to be nulled. Hence, this should not be considered a mistake

**Comment by QuestingPet** [comment]
Ahh good to know. I actually tried testing this exact scenario for a long time, but as far as I could tell I had to be proccing the down already by the time the projectile comes out, which means my auto attack has to already start going off and I have to just guess if the projectile is coming out (at least in solo). I eventually gave up on testing it.

If you’ve confirmed that the damage is nulled, then I’ll change it. Luckily this is actually the same behavior as the recent DDR (converging tiles) attack change they made where you can’t be damaged anymore if the core is out. I’m guessing that extends to *all* warden damage so I can make a widespread change to that effect. 

Won’t be able to fix this until later this week. Luckily your scenario should be relatively rare in the meantime. Thanks so much for reporting!
