### ISSUE TITLE
Party Plugin

### ISSUE THREAD

**Issue by monkeyd57** [QuestingPet/ToaMistakeTracker#5]
Would this be able to be used with the party plugin to see what other people's custom mistake text says? Would make as an awesome feature.

**Comment by QuestingPet** [comment]
Unfortunately adding networked behavior would require quite a bit of additional work. Additionally, I've kind of designed this plugin in such a way that all information can/should be gathered via the local client only, without needing to send data over the wire (which potentially opens it up to breaking some plugin guidelines). In this case, that might be fine, but I don't think I'll have the time required to add something like that in the foreseeable future. Sorry for the inconvenience :(

**Comment by monkeyd57** [comment]
no I appreciate the response and understand fully. Appreciate the
time/effort put into the current state of the plugin as im sure many do.
